In [1]:
import pandas as pd 
import numpy as np

url = "C:/Users/joth1/Documents/miniprojeto_pandas_sql/Nova pasta/202310Consorcios/202310Bens_Imoveis_Grupos.csv"

# Tente ler o arquivo usando utf-8 e, se falhar, tente latin-1
try:
    df = pd.read_csv(url, encoding='utf-8', sep=';')
except UnicodeDecodeError:
    df = pd.read_csv(url, encoding='latin-1', sep=';')

display(df)

,#Nome_da_Administradora,CNPJ_da_Administradora,Data_base,Código_do_grupo,Código_do_segmento,Número_da_assembléia_geral_ordinária,Valor_médio_do_bem,Índice_de_correção,Taxa_de_administração,Prazo_do_grupo_em_meses,Quantidade_de_cotas_ativas_em_dia,Quantidade_de_cotas_ativas_contempladas_inadimplentes,Quantidade_de_cotas_ativas_não_contempladas_inadimplentes,Quantidade_de_cotas_ativas_contempladas_no_mês,Quantidade_de_cotas_excluídas,Quantidade_de_cotas_ativas_quitadas,Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização
0,ITAÚ ADM DE CONSÓRCIOS LTDA ...,776,202310,00040,1,180,"272255,31",3,"18,65135",180,373,73,0,0,1721,431,15
1,ITAÚ ADM DE CONSÓRCIOS LTDA ...,776,202310,00041,1,180,"288848,90",3,"17,21443",180,422,84,0,0,1869,493,10
2,ITAÚ ADM DE CONSÓRCIOS LTDA ...,776,202310,00043,1,180,"269396,83",3,"18,29910",180,381,62,0,0,1795,433,10
3,ITAÚ ADM DE CONSÓRCIOS LTDA ...,776,202310,00044,1,180,"288651,90",3,"18,35775",180,385,86,0,0,1827,456,11
4,ITAÚ ADM DE CONSÓRCIOS LTDA ...,776,202310,00045,1,180,"258187,40",3,"18,75243",180,335,77,0,0,1776,393,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,BANRISUL S.A. ADM CONSÓRCIOS ...,92692979,202310,10062,1,5,"153125,00",3,"16,98270",200,529,0,49,2,166,0,8
2126,BANRISUL S.A. ADM CONSÓRCIOS ...,92692979,202310,10063,1,3,"87582,78",3,"20,00000",200,489,0,107,1,101,0,7
2127,BANRISUL S.A. ADM CONSÓRCIOS ...,92692979,202310,10064,1,2,"84259,87",3,"20,00000",200,600,0,0,4,45,0,5
2128,BANRISUL S.A. ADM CONSÓRCIOS ...,92692979,202310,10902,1,89,"183306,93",99,"12,00000",180,345,5,0,1,258,69,66
2129,GGS ADM CONS LTDA. ...,94187879,202310,4411,1,140,"138608,62",1,"22,31034",140,79,8,0,0,312,78,2